New integration tests
OneIdentity/bldr pull request #14
Opened 2022-02-14 22:22 UTC by wferi

2022-02-16 16:02 UTC, cemiarni requested changes

2022-02-16 16:02 UTC, cemiarni commented on test/integration/test_quilt_no_patch.py
> +    subprocess.check_call(['git', 'init'], cwd=quilt_project_dir)
The following lines should be moved to another function which name includes 'import' word. I think it could help to understand what their purpose is.

2022-02-16 16:02 UTC, cemiarni commented on test/integration/test_debian_build.py
> +    assert deb_build_options.issubset(set(content.split())), "The set of build options should not shrink."
IMHO: `deb_build_options == set(content.split())` should be better

2022-02-16 16:11 UTC, wferi commented on test/integration/test_debian_build.py
> +    assert deb_build_options.issubset(set(content.split())), "The set of build options should not shrink."
Dpkg-buildpackage adds the parallel=N build option automatically, so these sets aren't equal in general.

2022-02-16 16:15 UTC, wferi commented on test/integration/test_quilt_no_patch.py
> +    subprocess.check_call(['git', 'init'], cwd=quilt_project_dir)
Do you mean the rest of the definition body?

2022-02-16 16:24 UTC, cemiarni commented on test/integration/test_debian_build.py
> +    assert deb_build_options.issubset(set(content.split())), "The set of build options should not shrink."
I see.

2022-02-16 16:27 UTC, cemiarni requested changes

2022-02-16 16:27 UTC, cemiarni commented on test/integration/test_quilt_no_patch.py
> +    subprocess.check_call(['git', 'init'], cwd=quilt_project_dir)
yes, except the return line

2022-03-11 11:16 UTC, cemiarni approved these changes, later dismissed

2022-03-16 17:58 UTC, kocsob requested changes

2022-03-16 17:58 UTC, kocsob commented on test/integration/test_debian_build.py
> +    content = subprocess.check_output('dpkg-deb --fsys-tarfile {} | tar -Oxf- ./usr/share/doc/{}/deb_build_options.txt'.format(
The extracted deb file will be better for debugging as you made in another commit.

2022-03-21 11:09 UTC, kocsob approved these changes

2022-03-21 11:46 UTC, cemiarni approved these changes

2022-03-21 12:17 UTC, merged