Treat warnings as errors
OneIdentity/bldr pull request #16
Opened 2022-05-20 15:48 UTC by cemiarni

2022-07-13 12:03 UTC, andras-tim requested changes

2022-07-13 12:03 UTC, andras-tim commented on requirements.txt
> +# This file is autogenerated by pip-compile with python 3.6
I think we have to upgrade the requirements in a separate PR.

2022-07-15 05:40 UTC, wferi submitted a review, later dismissed
Merging this will automatically merge #16, so these are a single PR after all.

2022-07-15 12:07 UTC, andras-tim commented on requirements.txt
> +# This file is autogenerated by pip-compile with python 3.6
now OK, thank you

2022-07-15 12:08 UTC, andras-tim approved these changes

2022-07-15 12:31 UTC, wferi approved these changes

2022-07-15 20:44 UTC, merged