bldr/docker_utils.py: increase default timeout of docker API calls
OneIdentity/bldr pull request #36
Opened 2023-06-08 18:05 UTC by kocsob

In the communication of docker socket if there is no data transfer for 60 seconds then the docker API throws a timeout exception. It cause that the output stream of exec is stopped before the command running finished. The exec inspect cannot determine the exit code of the running command and tries to compare with None, which cause the following exception:

TypeError: '>' not supported between instances of 'NoneType' and 'int'

2023-06-08 18:38 UTC, wferi approved these changes, later dismissed

2023-06-09 06:35 UTC, wferi requested changes
> ### bldr/docker_utils.py: increase default timeout of docker API calls

Please drop the "default" qualifier: you increase the timeout of all our API calls by this (via the default timeout setting of the client, but that's implementation detail.)

> In the communication of docker socket if there is no data transfer for 60
seconds then the docker API throws a timeout exception.

But it does not, rather the evil streaming API swallows the timeout exception thrown by the socket code, silently ending the stream while the process is still running and thus hiding the actual cause. I'd consider this a plain bug.

> ### bldr/docker_utils.py: make the docker client usage explicit
>
> There was some lightening in the docker client initialization, but it could
be misleading and hard to use the same docker client everywhere.

What does "lightening" mean here? Do you mean shortcuts for user convenience? If so, I'd recommend "Uniformize Docker client initialization, because in the
following ..." wording instead.

2023-06-09 06:35 UTC, wferi commented on bldr/docker_utils.py
> +def create_docker_client(docker_timeout: Optional[int] = None) -> DockerClient:
docker_timeout: int = DEFAULT_DOCKER_TIMEOUT

2023-06-09 06:35 UTC, wferi commented on bldr/cli.py
> +            help="Default timeout for docker API calls, in seconds. (default: %(default)s)",
Calling it "default" implies that it is or can be overridden somewhere, but I can't find any traces of that. Please drop the "default" qualifier.

2023-06-09 11:49 UTC, cemiarni approved these changes

2023-06-09 12:11 UTC, wferi approved these changes

2023-06-09 12:45 UTC, merged